{% set version = "0.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-whisker
  version: {{ version|replace("-", "_") }}

source:
  fn: whisker_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/whisker_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/whisker/whisker_{{ version }}.tar.gz
  sha256: 7a86595be4f1029ec5d7152472d11b16175737e2777134e296ae97341bf8fba8

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('whisker')"           # [not win]
    - "\"%R%\" -e \"library('whisker')\""  # [win]

about:
  home: http://github.com/edwindj/whisker
  license: GPL-3
  summary: logicless templating, reuse templates in many programming languages including R
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - croth1
    - dbast
