appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ctFezqijHneH/J4AGNavy8m+R+rmxUPHq+sO7PKWrfgl9chJskZ/0WqpxYhBezjQmYgk2DMhNydxm5GGfXvVTEtSCx0FZqqWct+fNeMrvNbPCF471t21sGUQmkvEixoiJKrHNCXNjwtiVy8vmzDvmZqBcbq1zFPCkrqq63DNkdAKdyUA3mcbI8CSiFvUiPNGRODEM2aaOvTwuo+Mwjmg3Fz/giL9WyjnNJmUjmlbRB8FJ4j26y9EprHwTmdNNxsAz8UheDWccRsYAzNdKA0Grc/2HDB5EQatLatQ5zdiSbKkZkb00tZNkRvBwOQTlkxF0s2xDljb9sgOvr3BPYJg+0S8G5ugWYuDbVKGc6UOkuwBWzn+FdDW2oweRCpLtZTq0qKeYqxU6S9ciS4n39urIeoobQOqM9ruc480gkmXM7K8hWFb9td1geXkdIXOSr7b19ohiCy09RjlLN+i8j5ezQE4NkJQyBNT28n7+2rB5TuKlf+a8pOrFfL8SeGrRuVfAbKNGHIr9MohPJOe2Mb/ehsBERft7eDqHn8LQhd3NOEirjolEoxkIIghzD3ziNh0KelJL1IOrGBlRuUSrAIXFxp20z+0HdCdO9C62BsS4DGOPmtJaUeAYv10VKC8YXGjCRf+HP3uzQKXM0DIPbbn7ahuijNiXMOFIbzUSFmL5RA=}
bot:
  automerge: true
